version: '3.9'

services:
  app:
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: backend_postgres
    image: postgres
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: